apiVersion: v1
kind: Namespace
metadata:
  name:  dev
  labels:
    name:  dev


---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource
  namespace: dev
spec:
  hard:
    requests.cpu: "1"
    requests.memory: "1Gi"
    limits.cpu: "2"
    limits.memory: "2Gi"
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: deployment-test
  annotations:
    kubernetes.io/change-cause: se cambio el puerto
  labels:
    app: front
spec: #aqui se habla sobre el replica set
  revisionHistoryLimit: 8
  replicas: 2
  selector:
    matchLabels:
      app: front
  template: #aqui ya hablamos del pod
    metadata:
      labels:
        app: front # el label debe de cumplir con el selector del RS
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        resources:
            requests:
              memory: "500M"
              cpu: "0.5"
            limits:
              memory: "500M"
              cpu: "0.5"
            
        ports:
          - containerPort: 100
        
        
        