apiVersion: v1
kind: Pod
metadata:
  name: memory-demo2
spec:
  containers:
  - name: memory-demo-ctr
    image: polinux/stress
    resources:
      limits:
        cpu: "1"
        memory: "100Mi"
      requests:
        memory: "80Mi"
        cpu: "0.5"
    command: ["stress"]
    args: ["--vm","1","--vm-bytes","150M","--vm-hang","1"]
