apiVersion: v1
kind: PersistentVolume
metadata:
  name:  task
  labels:
    mysql: ready
spec:
  storageClassName: manual
  capacity:
    storage: 10G
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /test

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10G
  selector:
    matchLabels:
      mysql: ready