apiVersion: v1
kind: Secret
metadata:
  name:  login
stringData:
  username: root
  password: admin
type: Opaque
---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    name: mypod
spec:
  containers:
  - name: mypod
    image: nginx:alpine
    volumeMounts:
      - name: test
        mountPath: "/opt"
        readOnly: true
    resources:
      limits:
        memory: "20M"
        cpu: "500m"
    ports:
      - containerPort: 80
  volumes:
    - name: test
      secret:
        secretName: login
        items:
        - path: username.txt
          key: username
        - path:  pass.txt
          key: password
