apiVersion: v1
kind: Secret
metadata:
  name:  login
stringData:
  username: root
  password: admin
type: Opaque
---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    name: mypod
spec:
  containers:
  - name: mypod
    image: nginx:alpine
    readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 5

    livenessProbe:
        httpGet:
          port: 80
          path: /
        initialDelaySeconds: 10
        periodSeconds: 10

    env:
    - name:  USERNAME
      valueFrom:
          secretKeyRef:
            name: login
            key: username
    - name: PASSWORD
      valueFrom:
          secretKeyRef:
            name: login
            key: password
    volumeMounts:
      - name: test
        mountPath: "/opt"
        readOnly: true
    resources:
      limits:
        memory: "20M"
        cpu: "500m"
    ports:
      - containerPort: 80
  volumes:
    - name: test
      secret:
        secretName: login
        items:
        - path: username.txt
          key: username
        - path:  pass.txt
          key: password

